language: node_js
node_js: "12"

cache:
  yarn: true

stages:
  - Test
  - name: Release
    if: repo = "edouardhienrichs/free-press" AND tag IS present

jobs:
  include:
    - stage: Test
      name: Unit Tests
      after_script:
        - ./node_modules/.bin/coveralls < ./coverage/lcov.info

    - stage: Release
      name: Unsigned Extension
      script: skip
      before_deploy:
        - yarn build:release
        - yarn ci:generate:release_notes
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        edge:
          branch: master
        file: ./free-press-unsigned.zip
        release_notes_file: ./RELEASE_NOTES.md
        on:
          repo: edouardhienrichs/free-press
          tags: true

# Limit branches builds to "master", "develop" and tags ones:
branches:
  only:
    - develop
    - master
    - /^v\d+\.\d+\.\d+(-(alpha|beta)\.\d+)?$/

notifications:
  email:
    on_failure: change
    on_success: never
